### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by enhany** [Xumeiquer/tmd#1]
Hello, 
please explain how to upload config file (API KEY) to docker?
what path inside container?

**Comment by dexteon** [comment]
Following up with the same question. Can you explain how this part works? I see your tmd.yml but im not sure how to access it on docker or reference it?

**Comment by dexteon** [comment]
`E:\Scripts\tmd>docker run --rm -it -v E:\Scripts\tmd\tmd.yml:/app/tmd.yml ghcr.io/xumeiquer/tmd download topic
2024/09/29 03:58:34 WARN configuration file not found
2024/09/29 03:58:34 ERROR found an error while initializing TDLib msg="API ID is not defined"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x83f906]

goroutine 1 [running]:
github.com/Xumeiquer/tmd/internal/tg.(*TGClient).Authenticate(0xc000146640)
        github.com/Xumeiquer/tmd/internal/tg/client.go:56 +0x166
github.com/Xumeiquer/tmd/cmd.downloadTopicCmdEx(0xc00018a400?, {0x1e076ad?, 0x4?, 0x1e076b1?})
        github.com/Xumeiquer/tmd/cmd/downloadTopic.go:33 +0xd2
github.com/spf13/cobra.(*Command).execute(0x26e7680, {0x27af4e0, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x26e6540)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/Xumeiquer/tmd/cmd.Execute()
        github.com/Xumeiquer/tmd/cmd/root.go:50 +0x1a
main.main()
        ./main.go:9 +0xf

E:\Scripts\tmd>`

This is the error.

I tried adding a tmd.yml based on your example to the directory i was running tmd from to no avail.

**Comment by Xumeiquer** [comment]
The path where TMD tries to find the configuration is defined here https://github.com/Xumeiquer/tmd/blob/main/cmd/root.go#L67-L71

**Comment by justingoldberg** [comment]
where is the file format documented or is there any example?
